# Generated by Django 4.2.16 on 2025-09-06 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('driver_post', '0005_alter_city_unique_together'),
        ('delivery', '0002_alter_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='receiver_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='dropoff_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_deliveries', to='driver_post.city'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_deliveries', to='driver_post.city'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='delivery.delivery')),
            ],
        ),
    ]
