# Generated by Django 4.2.16 on 2025-09-16 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0003_remove_delivery_receiver_id_delivery_dropoff_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
