# Generated by Django 4.2.16 on 2025-09-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.FloatField(),
        ),
    ]
