# Generated by Django 4.2.16 on 2025-11-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_package_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='estimated_delivery_time',
        ),
    ]
