# Generated by Django 4.2.16 on 2025-05-24 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Wallet', 'Wallet')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('refund_status', models.CharField(choices=[('None', 'None'), ('Requested', 'Requested'), ('Processed', 'Processed'), ('Denied', 'Denied')], default='None', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='delivery.delivery')),
            ],
        ),
    ]
