# Generated by Django 4.2.16 on 2025-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_user_id_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cod_notes',
            field=models.TextField(blank=True, help_text='Notes for COD negotiation', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='easypaisa_phone',
            field=models.CharField(blank=True, help_text='Phone number for EasyPaisa', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash on Delivery'), ('EasyPaisa', 'EasyPaisa')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_pay_payment_7d17d2_idx'),
        ),
    ]
