# Generated by Django 4.2.16 on 2025-10-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_package_weight'),
        ('payment', '0003_payment_cod_notes_payment_easypaisa_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='delivery.deliverylog'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payment_pay_payment_51dee4_idx'),
        ),
    ]
