# Generated by Django 4.2.16 on 2025-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash on Delivery'), ('EasyPaisa', 'EasyPaisa')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
