# Generated by Django 4.2.16 on 2025-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='delivery_log',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='easypaisa_phone',
        ),
        migrations.AddField(
            model_name='payment',
            name='driver_easypaisa_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_notes',
            field=models.TextField(blank=True, help_text='Notes from sender, e.g., transaction ref', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cod_notes',
            field=models.TextField(blank=True, help_text='Notes for COD', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash on Delivery'), ('EasyPaisa', 'EasyPaisa')], max_length=20),
        ),
    ]
