# Generated by Django 4.2.16 on 2025-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id'], name='notificatio_user_id_971103_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivery_id'], name='notificatio_deliver_69395b_idx'),
        ),
    ]
