# Generated by Django 4.2.16 on 2025-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driververification',
            name='cnic_image',
            field=models.ImageField(default=1, upload_to='cnic_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driververification',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driververification',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
