# Generated by Django 4.2.16 on 2025-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_verification', '0002_driververification_cnic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driververification',
            name='formatted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
