# Generated by Django 4.2.16 on 2025-05-24 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.JSONField()),
                ('end_location', models.JSONField()),
                ('waypoints', models.JSONField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.IntegerField()),
                ('actual_time', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.delivery')),
            ],
        ),
    ]
