# Generated by Django 4.2.16 on 2025-09-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_receiver_id'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='actual_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='waypoints',
        ),
        migrations.AddField(
            model_name='route',
            name='path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='delivery_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='delivery.delivery'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['delivery_id'], name='route_route_deliver_bcadf7_idx'),
        ),
    ]
