# Generated by Django 4.2.16 on 2025-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_route_actual_time_remove_route_end_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
