# Generated by Django 4.2.16 on 2025-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='log_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
