# Generated by Django 4.2.16 on 2025-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='easypaisa_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
