# Generated by Django 4.2.16 on 2025-11-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driverprofile_easypaisa_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'phone_number'), name='unique_first_last_phone'),
        ),
    ]
