# Generated by Django 4.2.16 on 2025-11-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_unique_first_last_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_first_last_phone',
        ),
    ]
