# Generated by Django 4.2.16 on 2025-08-11 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_document',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.ImageField(blank=True, upload_to='vehicle_insurance/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Review', 'Under Review')], default='Under Review', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'status'], name='vehicle_veh_user_id_4dc372_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicle_veh_license_0e3923_idx'),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicle.vehicle'),
        ),
    ]
