# Generated by Django 4.2.16 on 2025-08-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehiclelog_rename_user_id_vehicle_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='vehicle_type_id',
            new_name='type_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type_id',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicle.vehicletype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
