# Generated by Django 4.2.16 on 2025-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_rename_vehicle_type_id_vehicletype_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicle_veh_license_0e3923_idx',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_plate',
            new_name='license_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_document',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_number'], name='vehicle_veh_license_4c1c35_idx'),
        ),
    ]
