# Generated by Django 4.2.16 on 2025-08-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_capacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('approved', 'approved'), ('pending', 'pending')], default='Active', max_length=20),
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
