# Generated by Django 4.2.16 on 2025-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_remove_vehicle_vehicle_type_vehicle_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicle_veh_license_4c1c35_idx',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_number',
            new_name='number_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='max_weight',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['number_plate'], name='vehicle_veh_number__2a69d4_idx'),
        ),
    ]
