# Generated by Django 4.2.16 on 2025-08-06 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('driver_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='driverpost',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='driverpost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='driverpost',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='driverpost',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='driverpost',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_posts', to='vehicle.vehicle'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name', 'country'], name='driver_post_name_1cfd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpost',
            index=models.Index(fields=['user', 'status'], name='driver_post_user_id_345c50_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpost',
            index=models.Index(fields=['start_city', 'end_city'], name='driver_post_start_c_a06069_idx'),
        ),
        migrations.AddIndex(
            model_name='driverpost',
            index=models.Index(fields=['departure_date'], name='driver_post_departu_2d1886_idx'),
        ),
        migrations.AddField(
            model_name='postlog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='driver_post.driverpost'),
        ),
    ]
