# Generated by Django 4.2.16 on 2025-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_post', '0002_postlog_rename_user_id_driverpost_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverpost',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired'), ('Booked', 'Booked')], default='Active', max_length=20),
        ),
    ]
