# Generated by Django 4.2.16 on 2025-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_post', '0003_alter_driverpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state', 'country')},
        ),
    ]
