# Generated by Django 4.2.16 on 2025-09-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_post', '0004_alter_city_name_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
