# Generated by Django 4.2.16 on 2025-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_post', '0005_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
