# Generated by Django 4.2.16 on 2025-11-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_post', '0006_alter_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpost',
            name='available_capacity',
        ),
    ]
